conky.config = {
    background = true,
    update_interval = 1,
    double_buffer = true,

    own_window = true,
    own_window_type = 'override',
    own_window_transparent = true,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',

    alignment = 'top_left',
    gap_x = 20,
    gap_y = 40,

    minimum_width = 200,
    maximum_width = 900,

    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    use_xft = true,
    font = 'JetBrains Mono:size=10',
};

conky.text = [[
RAM: $mem / $memmax
Disk: ${fs_used /} / ${fs_size /}

${font JetBrains Mono:bold:size=10}Tasks:${font}
${exec cat ~/projects/obsidian/personal\ notes/Things\ to\ do.md}
]];

